[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom-term.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn"
four = "closed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"

[buildPlans.iosevka-custom-term.variants.italic]
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
r = "top-serifed"
v = "cursive"
w = "cursive-motion-serifed"
x = "straight-motion-serifed"
y = "cursive"
z = "curly-serifless"

[buildPlans.iosevka-custom-term.slopes]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-custom-fixed]
family = "Iosevka Custom Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom-fixed.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn"
four = "closed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"

[buildPlans.iosevka-custom-fixed.variants.italic]
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
r = "top-serifed"
v = "cursive"
w = "cursive-motion-serifed"
x = "straight-motion-serifed"
y = "cursive"
z = "curly-serifless"

[buildPlans.iosevka-custom-fixed.slopes]
upright = "normal"
italic = "italic"
