[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-custom-term.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn"
four = "closed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"

[buildPlans.iosevka-custom-term.variants.italic]
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
v = "cursive"
w = "cursive"
x = "curly-serifless"
y = "cursive"
z = "curly-serifless"

[buildPlans.iosevka-custom-term.ligations]
inherits = "dlig"

[buildPlans.iosevka-custom-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom-term.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom-term.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-custom-fixed]
family = "Iosevka Custom Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-custom-fixed.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn"
four = "closed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"

[buildPlans.iosevka-custom-fixed.variants.italic]
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
v = "cursive"
w = "cursive"
x = "curly-serifless"
y = "cursive"
z = "curly-serifless"

[buildPlans.iosevka-custom-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
