[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom-term.variants.design]
capital-d = "more-rounded-serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching"
capital-m = "flat-bottom"
capital-q = "crossing"
capital-w = "straight-flat-top"
j = "serifless"
k = "symmetric-touching"
l = "serifed-tailed"
w = "straight-flat-top"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching"
cyrl-capital-u = "straight-turn"
two = "curly-neck"
four = "closed"
seven = "straight-serifed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"
percent = "rings-continuous-slash"

[buildPlans.iosevka-custom-term.variants.italic]
capital-q = "curly-tailed"
h = "tailed"
i = "serifed-flat-tailed"
j = "serifed"
k = "cursive"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
r = "top-serifed"
w = "cursive-motion-serifed"
x = "straight-motion-serifed"
y = "cursive-motion-serifed"
latn-epsilon = "serifless"

[buildPlans.iosevka-custom-term.slopes]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-custom-fixed]
family = "Iosevka Custom Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom-fixed.variants.design]
capital-d = "more-rounded-serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "symmetric-touching"
capital-m = "flat-bottom"
capital-q = "crossing"
capital-w = "straight-flat-top"
j = "serifless"
k = "symmetric-touching"
l = "serifed-tailed"
w = "straight-flat-top"
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-ka = "symmetric-touching"
cyrl-capital-u = "straight-turn"
two = "curly-neck"
four = "closed"
seven = "straight-serifed"
asterisk = "hex-low"
underscore = "above-baseline"
at = "short"
percent = "rings-continuous-slash"

[buildPlans.iosevka-custom-fixed.variants.italic]
capital-q = "curly-tailed"
h = "tailed"
i = "serifed-flat-tailed"
j = "serifed"
k = "cursive"
m = "tailed"
n = "tailed"
p = "motion-serifed"
q = "diagonal-tailed"
r = "top-serifed"
w = "cursive-motion-serifed"
x = "straight-motion-serifed"
y = "cursive-motion-serifed"
latn-epsilon = "serifless"

[buildPlans.iosevka-custom-fixed.slopes]
upright = "normal"
italic = "italic"
